
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 14 16:33:42 IST 2011
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int LCBR = 8;
  public static final int LTE = 42;
  public static final int UMINUS = 49;
  public static final int INTEGER = 47;
  public static final int SEMI = 12;
  public static final int CONTINUE = 22;
  public static final int INT = 5;
  public static final int MINUS = 44;
  public static final int STATIC = 13;
  public static final int LT = 41;
  public static final int LP = 7;
  public static final int COMMA = 4;
  public static final int CLASS = 3;
  public static final int RP = 11;
  public static final int PLUS = 45;
  public static final int MULTIPLY = 32;
  public static final int QUOTE = 48;
  public static final int ASSIGN = 18;
  public static final int IF = 24;
  public static final int THIS = 29;
  public static final int DOT = 19;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int LAND = 38;
  public static final int RCBR = 10;
  public static final int LB = 6;
  public static final int RETURN = 26;
  public static final int EQUAL = 35;
  public static final int TRUE = 46;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int RB = 9;
  public static final int LOR = 40;
  public static final int NULL = 30;
  public static final int MOD = 31;
  public static final int BREAK = 21;
  public static final int VOID = 15;
  public static final int GTE = 37;
  public static final int ELSE = 23;
  public static final int WHILE = 25;
  public static final int NEQUAL = 33;
  public static final int CLASS_ID = 16;
  public static final int EXTENDS = 27;
  public static final int STRING = 14;
  public static final int LNEG = 39;
  public static final int FALSE = 43;
  public static final int GT = 36;
  public static final int LENGTH = 20;
}

