
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 09 01:03:36 IST 2011
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int LCBR = 10;
  public static final int LTE = 40;
  public static final int UMINUS = 49;
  public static final int INTEGER = 47;
  public static final int SEMI = 12;
  public static final int CONTINUE = 17;
  public static final int INT = 14;
  public static final int MINUS = 42;
  public static final int STATIC = 25;
  public static final int LT = 39;
  public static final int LP = 8;
  public static final int COMMA = 4;
  public static final int CLASS = 22;
  public static final int RP = 9;
  public static final int PLUS = 43;
  public static final int MULTIPLY = 30;
  public static final int QUOTE = 48;
  public static final int ASSIGN = 2;
  public static final int IF = 19;
  public static final int THIS = 26;
  public static final int ID = 46;
  public static final int DOT = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int LAND = 36;
  public static final int RCBR = 11;
  public static final int LB = 6;
  public static final int RETURN = 21;
  public static final int EQUAL = 33;
  public static final int TRUE = 44;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int RB = 7;
  public static final int LOR = 38;
  public static final int NULL = 28;
  public static final int MOD = 29;
  public static final int BREAK = 16;
  public static final int VOID = 27;
  public static final int GTE = 35;
  public static final int ELSE = 18;
  public static final int WHILE = 20;
  public static final int NEQUAL = 31;
  public static final int CLASS_ID = 45;
  public static final int EXTENDS = 23;
  public static final int STRING = 15;
  public static final int LNEG = 37;
  public static final int FALSE = 41;
  public static final int GT = 34;
  public static final int LENGTH = 5;
}

